### ISSUE TITLE
"panic: No main container in the file" when trying to run on monkey island 2

### ISSUE THREAD

**Issue by mankeli** [ktzar/scummatlas#18]
I guess I have some different version of monkey island 2 than what this was made for.

```
8b053669abdeb7e198597df61423e493  adlib.ims
3686cf8f89e102ececf4366e1d2c8126  monkey2.000
50993d719990d2e212c50a915f6c50da  monkey2.001
58d34b2a6db171517340cb883618e419  monkey2.exe
98c9453b486e9cbff95c97c480c1a8d9  roland.ims
09ba62c3bc9f2bdc50868466cc4576b5  sounblas.ims
0c0a385da45ac811b23bbd47c9935990  speaker.ims
```

**Comment by iliocatallo** [comment]
Ditto. I'm having the exact same problem

**Comment by ktzar** [comment]
Hello! Thanks for testing it. I got the same issue with a version I downloaded from some website, but the one in "the-eye" (https://the-eye.eu/public/Games/ScummVM/Working/Monkey%20Island%202%20LeChuck%27s%20Revenge%20%28Floppy%20DOS%20VGA%29.zip) does work file.

**Comment by mankeli** [comment]
Hi! Thanks for the info. I get quite a lot of warnings while exporting but dirs get filled with files. Awesome :)

**Comment by JaimeObregon** [comment]
Thank you. The previous link directing to `the-eye.eu` is no longer functional. However, this new one is and using it I have been able to download "Monkey Island 2: LeChuck's Revenge" and process it through scummatlas successfully:

https://gamesnostalgia.com/download/monkey-island-2-lechucks-revenge/1615

Also with "The Secret of Monkey Island":

https://gamesnostalgia.com/download/secret-of-monkey-island/3122
